In [1]:
import numpy as np
import time

In [10]:
a = np.random.random(1000000)
b = np.random.random(1000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Time taken by np.dot is " + str(1000*(toc-tic)) + "\n\n")

c = 0
tic = time.time()
for i in range(a.size):
    c+=a[i]*b[i]
toc = time.time()
print(c)
print("Time taken by for loop is " + str(1000*(toc-tic)))

250023.14436579758
Time taken by np.dot is 1.5728473663330078


250023.14436579865
Time taken by for loop is 585.9959125518799


In [25]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [26]:
print(c)
print(a)
print(b)

[[ 0.03632149 -0.07810957 -0.02730961]
 [ 0.99335372  0.05769023  0.45113658]
 [ 0.27451529  0.17607497  0.21610544]]
[[-0.6531047   1.4045053   0.49106015]
 [ 1.18767104  0.06897545  0.53938677]
 [ 0.76815174  0.49269493  0.60470863]]
[[-0.05561358]
 [ 0.83638793]
 [ 0.35737118]]


In [29]:
import math
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1/(1+np.exp(-1*x))
    ### END CODE HERE ###
    
    return s

In [30]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])