In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [1,0], [0,1], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivative_sigmoid(z):
    return sigmoid(z)*(1-sigmoid(z))

In [12]:
# No hidden layer weight
w = 2*np.random.random((2,1)) - 1
b = 2*np.random.random(1) - 1

In [13]:
print(w,b)

[[-0.08440144]
 [ 0.61748472]] [0.16040035]


In [14]:
# forward propagation without any hidden layer
output0 = X
output = sigmoid(np.dot(output0, w)+b)
print(output)

[[0.54001433]
 [0.51899059]
 [0.68522412]
 [0.66674143]]


In [15]:
# One Hidden Layer Introduced
wh = 2*np.random.random((2,2)) - 1
bh = 2*np.random.random((1,2)) - 1
w0 = 2*np.random.random((2,1)) - 1
b0 = 2*np.random.random((1,1)) - 1

In [16]:
# Forward propagation with one hidden layer
output0 = X
outputHidden = sigmoid(np.dot(output0, wh)+bh)
output = sigmoid(np.dot(outputHidden, w0) + b0)
print(output)

[[0.56269796]
 [0.57228789]
 [0.55755838]
 [0.56832824]]
